"""Generate synthetic VCZ fixtures + phenotypes for the validation suite.

Two sizes:

- ``small`` — 200 diploid samples, ~500 biallelic variants. Used by
  qctool, PLINK 1.9, bgenix, REGENIE.
- ``large`` — 5000 diploid samples, ~20000 variants. Used by BOLT-LMM,
  which requires realistic sample counts to fit a null model.

Each fixture writes:

- ``data/<size>_unphased.vcz/`` and ``data/<size>_phased.vcz/`` — two
  Zarr v2 VCZ stores produced by ``bio2zarr.tskit.convert`` from the
  same simulation; only ``call_genotype_phased`` differs.
- ``data/<size>.pheno.tsv`` — a REGENIE/BOLT-style phenotype file
  (``FID IID Y1``) generated by tstrait from the source tree sequence.
  Shared between the phased and unphased stores.
- ``data/<size>.vcz.ready`` — marker file (sibling to the stores)
  signalling that both stores were built; consumed by the Makefile.

Phenotypes come from ``tstrait`` over the *source tree sequence* so the
genetic architecture is realistic enough that LMM tools can fit a null
model. The phenotype values themselves are not load-bearing for our
checks (we compare allele frequencies, not effect sizes).
"""

from __future__ import annotations

import dataclasses
import logging
import pathlib
import shutil

import bio2zarr.tskit as b2z_tskit
import click
import msprime
import numpy as np
import pandas as pd
import tskit
import tstrait
import zarr

logger = logging.getLogger(__name__)

HERE = pathlib.Path(__file__).parent
DATA_DIR = HERE / "data"

POPULATION_SIZE = 10_000
MUTATION_RATE = 1e-7
RECOMBINATION_RATE = 1e-8


@dataclasses.dataclass(frozen=True)
class FixtureSpec:
    name: str
    num_samples: int
    seq_length: float
    target_variants: int
    seed: int


SPECS: dict[str, FixtureSpec] = {
    "small": FixtureSpec(
        name="small",
        num_samples=200,
        seq_length=5e4,
        target_variants=1000,
        seed=42,
    ),
    "large": FixtureSpec(
        name="large",
        num_samples=5000,
        seq_length=5e5,
        target_variants=20_000,
        seed=43,
    ),
}


def simulate(spec: FixtureSpec) -> tskit.TreeSequence:
    ts = msprime.sim_ancestry(
        samples=spec.num_samples,
        sequence_length=spec.seq_length,
        recombination_rate=RECOMBINATION_RATE,
        population_size=POPULATION_SIZE,
        random_seed=spec.seed,
    )
    ts = msprime.sim_mutations(ts, rate=MUTATION_RATE, random_seed=spec.seed)
    logger.info(
        "Simulated %s: %d samples (diploid), %d variants",
        spec.name,
        spec.num_samples,
        ts.num_sites,
    )
    return ts


VARIANT_ID_BUCKETS: tuple[str, ...] = (
    "rs{i}",
    "rs_var_{i:08d}",
    "rs_variant_{i:010d}_chr_{c:02d}_pos_{p:010d}",
)
"""Three format strings cycled across the variants axis to produce a
deterministic mix of short (3–7 byte), medium (15 byte), and long
(~46 byte) variant IDs. Lengths stay below
:class:`vcztools.bgen.BgenEncoder`'s default ``rsid_max=64`` so the
encoder's defaults still apply when this fixture is fed through it.
"""


def _make_variant_ids(positions: np.ndarray, contigs: np.ndarray) -> np.ndarray:
    out = np.empty(positions.shape, dtype=np.dtypes.StringDType())
    for i in range(positions.size):
        template = VARIANT_ID_BUCKETS[i % len(VARIANT_ID_BUCKETS)]
        out[i] = template.format(i=i, c=int(contigs[i]), p=int(positions[i]))
    return out


def write_vcz(ts: tskit.TreeSequence, vcz_path: pathlib.Path, *, phased: bool) -> None:
    if vcz_path.exists():
        # bio2zarr refuses to overwrite an existing store; clean up first.
        shutil.rmtree(vcz_path)
    b2z_tskit.convert(
        ts,
        str(vcz_path),
        variants_chunk_size=1000,
        samples_chunk_size=1000,
        worker_processes=0,
        show_progress=False,
    )
    group = zarr.open_group(str(vcz_path), mode="r+")
    # tskit data is always phased; bio2zarr writes call_genotype_phased
    # = True. The unphased variant flattens the flag so vcztools emits
    # standard unphased BGEN (and PLINK, which has no phase concept).
    # The phased variant leaves the flag set, exercising vcztools'
    # phased-BGEN code path against downstream tools.
    if not phased and "call_genotype_phased" in group.array_keys():
        group["call_genotype_phased"][...] = False
    # bio2zarr.tskit.convert does not populate variant_id (tskit uses
    # positional numbering, not RS-style IDs). Inject deterministic
    # variable-length IDs so the downstream-tool round-trip checks have
    # a non-trivial signal to verify.
    positions = group["variant_position"][:]
    contigs = group["variant_contig"][:]
    ids = _make_variant_ids(positions, contigs)
    variants_chunk = group["variant_position"].chunks[0]
    variant_id_arr = group.create_array(
        "variant_id",
        shape=ids.shape,
        chunks=(variants_chunk,),
        dtype=np.dtypes.StringDType(),
    )
    variant_id_arr[:] = ids
    # vcztools uses the zarr-v2 `_ARRAY_DIMENSIONS` attribute (and the
    # v3 `dimension_names` metadata) to identify the variants axis on
    # every variant-scoped field. bio2zarr writes v2 by default, so
    # set the v2 attribute on the array we just appended.
    variant_id_arr.attrs["_ARRAY_DIMENSIONS"] = ["variants"]
    logger.info("Wrote VCZ store at %s", vcz_path)


def simulate_phenotype(
    ts: tskit.TreeSequence,
    spec: FixtureSpec,
    out_path: pathlib.Path,
) -> None:
    # 100 causal sites, heritability 0.5 — enough genetic signal that a
    # null model fit is well-conditioned.
    n_causal = min(100, ts.num_sites)
    model = tstrait.trait_model(distribution="normal", mean=0, var=1)
    sim_result = tstrait.sim_phenotype(
        ts=ts,
        num_causal=n_causal,
        model=model,
        h2=0.5,
        random_seed=spec.seed,
    )
    pheno = sim_result.phenotype
    # bio2zarr.tskit.convert names individuals tsk_0, tsk_1, ...; view-
    # bgen writes those into BGEN's .sample file as ID_1=ID_2=tsk_N
    # (so REGENIE/BOLT see FID=IID=tsk_N for BGEN input). view-plink
    # writes FID="0", IID=tsk_N into the .fam (a different FID
    # convention). We write the pheno file in the BGEN convention here;
    # the conftest fixtures emit a remapped FID="0" variant when a
    # test consumes the PLINK fileset.
    iids = [f"tsk_{int(i)}" for i in pheno["individual_id"]]
    df = pd.DataFrame(
        {
            "FID": iids,
            "IID": iids,
            "Y1": pheno["phenotype"].astype(np.float64),
        }
    )
    df.to_csv(out_path, sep="\t", index=False)
    logger.info("Wrote phenotype file %s (%d rows)", out_path, len(df))


def build_fixture(size: str) -> None:
    spec = SPECS[size]
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    unphased_path = DATA_DIR / f"{size}_unphased.vcz"
    phased_path = DATA_DIR / f"{size}_phased.vcz"
    pheno_path = DATA_DIR / f"{size}.pheno.tsv"

    ts = simulate(spec)
    # Two stores per size, one msprime simulation. The fixtures share
    # genotypes; only `call_genotype_phased` differs.
    write_vcz(ts, unphased_path, phased=False)
    write_vcz(ts, phased_path, phased=True)
    simulate_phenotype(ts, spec, pheno_path)

    # Single marker per size: presence indicates both stores are
    # complete. Lives outside the VCZ stores so zarr doesn't warn
    # about unrecognised hierarchy components.
    marker = DATA_DIR / f"{size}.vcz.ready"
    marker.write_text(
        f"size={size}\nnum_samples={spec.num_samples}\n"
        f"num_variants={ts.num_sites}\nseed={spec.seed}\n"
    )
    logger.info(
        "Fixture %s ready (unphased=%s, phased=%s)", size, unphased_path, phased_path
    )


def check_fixture(size: str) -> None:
    spec = SPECS[size]
    pheno_path = DATA_DIR / f"{size}.pheno.tsv"
    marker = DATA_DIR / f"{size}.vcz.ready"

    if not marker.exists():
        raise SystemExit(f"missing fixture marker {marker}")
    if not pheno_path.exists():
        raise SystemExit(f"missing phenotype file {pheno_path}")

    for variant in ("unphased", "phased"):
        vcz_path = DATA_DIR / f"{size}_{variant}.vcz"
        group = zarr.open_group(str(vcz_path), mode="r")
        n_samples = group["sample_id"].shape[0]
        n_variants = group["variant_position"].shape[0]
        if n_samples != spec.num_samples:
            raise SystemExit(
                f"{size}_{variant}: expected {spec.num_samples} samples, "
                f"got {n_samples}"
            )
        print(f"{size}_{variant}: ok ({n_samples} samples, {n_variants} variants)")


@click.command(help=__doc__)
@click.option(
    "--size",
    type=click.Choice(list(SPECS)),
    default=None,
    help="Which fixture to generate.",
)
@click.option(
    "--check",
    is_flag=True,
    help="Verify existing fixtures rather than regenerate.",
)
@click.option(
    "--all",
    "all_sizes",
    is_flag=True,
    help="Generate every fixture.",
)
def main(size: str | None, check: bool, all_sizes: bool) -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    if check:
        targets = [size] if size is not None else list(SPECS)
        for t in targets:
            check_fixture(t)
        return

    if all_sizes:
        targets = list(SPECS)
    elif size is not None:
        targets = [size]
    else:
        raise click.UsageError("either --size or --all is required")
    for t in targets:
        build_fixture(t)


if __name__ == "__main__":
    main()
