"""Generate synthetic VCZ fixtures + phenotypes for the validation suite.

Two sizes:

- ``small`` — 200 diploid samples, ~500 biallelic variants. Used by
  qctool, PLINK 1.9, bgenix, REGENIE.
- ``large`` — 5000 diploid samples, ~20000 variants. Used by BOLT-LMM,
  which requires realistic sample counts to fit a null model.

Each fixture writes:

- ``data/<size>.vcz/`` — a Zarr v2 VCZ store produced by
  ``bio2zarr.tskit.convert``.
- ``data/<size>.pheno.tsv`` — a REGENIE/BOLT-style phenotype file
  (``FID IID Y1``) generated by tstrait from the source tree sequence.
- ``data/<size>.vcz/.ready`` — marker file so the Makefile can detect
  completion.

Phenotypes come from ``tstrait`` over the *source tree sequence* so the
genetic architecture is realistic enough that LMM tools can fit a null
model. The phenotype values themselves are not load-bearing for our
checks (we compare allele frequencies, not effect sizes).
"""

from __future__ import annotations

import argparse
import dataclasses
import logging
import pathlib
import shutil

import bio2zarr.tskit as b2z_tskit
import msprime
import numpy as np
import pandas as pd
import tskit
import tstrait
import zarr

logger = logging.getLogger(__name__)

HERE = pathlib.Path(__file__).parent
DATA_DIR = HERE / "data"

POPULATION_SIZE = 10_000
MUTATION_RATE = 1e-7
RECOMBINATION_RATE = 1e-8


@dataclasses.dataclass(frozen=True)
class FixtureSpec:
    name: str
    num_samples: int
    seq_length: float
    target_variants: int
    seed: int


SPECS: dict[str, FixtureSpec] = {
    "small": FixtureSpec(
        name="small",
        num_samples=200,
        seq_length=5e4,
        target_variants=1000,
        seed=42,
    ),
    "large": FixtureSpec(
        name="large",
        num_samples=5000,
        seq_length=5e5,
        target_variants=20_000,
        seed=43,
    ),
}


def simulate(spec: FixtureSpec) -> tskit.TreeSequence:
    ts = msprime.sim_ancestry(
        samples=spec.num_samples,
        sequence_length=spec.seq_length,
        recombination_rate=RECOMBINATION_RATE,
        population_size=POPULATION_SIZE,
        random_seed=spec.seed,
    )
    ts = msprime.sim_mutations(ts, rate=MUTATION_RATE, random_seed=spec.seed)
    logger.info(
        "Simulated %s: %d samples (diploid), %d variants",
        spec.name,
        spec.num_samples,
        ts.num_sites,
    )
    return ts


def write_vcz(ts: tskit.TreeSequence, vcz_path: pathlib.Path) -> None:
    if vcz_path.exists():
        # bio2zarr refuses to overwrite an existing store; clean up first.
        shutil.rmtree(vcz_path)
    b2z_tskit.convert(
        ts,
        str(vcz_path),
        variants_chunk_size=1000,
        samples_chunk_size=1000,
        worker_processes=0,
        show_progress=False,
    )
    # tskit data is always phased; bio2zarr writes call_genotype_phased
    # = True. Many downstream tools (qctool in particular) don't handle
    # our phased BGEN layout cleanly, and real-world genotyping-array
    # data is unphased anyway, so flatten the phasing flag here.
    group = zarr.open_group(str(vcz_path), mode="r+")
    if "call_genotype_phased" in group.array_keys():
        group["call_genotype_phased"][...] = False
    logger.info("Wrote VCZ store at %s", vcz_path)


def simulate_phenotype(
    ts: tskit.TreeSequence,
    spec: FixtureSpec,
    out_path: pathlib.Path,
) -> None:
    # 100 causal sites, heritability 0.5 — enough genetic signal that a
    # null model fit is well-conditioned.
    n_causal = min(100, ts.num_sites)
    model = tstrait.trait_model(distribution="normal", mean=0, var=1)
    sim_result = tstrait.sim_phenotype(
        ts=ts,
        num_causal=n_causal,
        model=model,
        h2=0.5,
        random_seed=spec.seed,
    )
    pheno = sim_result.phenotype
    # bio2zarr.tskit.convert names individuals tsk_0, tsk_1, ...; view-
    # bgen writes those into BGEN's .sample file as ID_1=ID_2=tsk_N
    # (so REGENIE/BOLT see FID=IID=tsk_N for BGEN input). view-plink
    # writes FID="0", IID=tsk_N into the .fam (a different FID
    # convention). We write the pheno file in the BGEN convention here;
    # the conftest fixtures emit a remapped FID="0" variant when a
    # test consumes the PLINK fileset.
    iids = [f"tsk_{int(i)}" for i in pheno["individual_id"]]
    df = pd.DataFrame(
        {
            "FID": iids,
            "IID": iids,
            "Y1": pheno["phenotype"].astype(np.float64),
        }
    )
    df.to_csv(out_path, sep="\t", index=False)
    logger.info("Wrote phenotype file %s (%d rows)", out_path, len(df))


def build_fixture(size: str) -> None:
    spec = SPECS[size]
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    vcz_path = DATA_DIR / f"{size}.vcz"
    pheno_path = DATA_DIR / f"{size}.pheno.tsv"

    ts = simulate(spec)
    write_vcz(ts, vcz_path)
    simulate_phenotype(ts, spec, pheno_path)

    # Marker file lives outside the VCZ store so zarr doesn't warn
    # about unrecognised hierarchy components.
    marker = DATA_DIR / f"{size}.vcz.ready"
    marker.write_text(
        f"size={size}\nnum_samples={spec.num_samples}\n"
        f"num_variants={ts.num_sites}\nseed={spec.seed}\n"
    )
    logger.info("Fixture %s ready at %s", size, vcz_path)


def check_fixture(size: str) -> None:
    spec = SPECS[size]
    vcz_path = DATA_DIR / f"{size}.vcz"
    pheno_path = DATA_DIR / f"{size}.pheno.tsv"

    if not (DATA_DIR / f"{size}.vcz.ready").exists():
        raise SystemExit(f"missing or incomplete fixture at {vcz_path}")
    if not pheno_path.exists():
        raise SystemExit(f"missing phenotype file {pheno_path}")

    group = zarr.open_group(str(vcz_path), mode="r")
    n_samples = group["sample_id"].shape[0]
    n_variants = group["variant_position"].shape[0]
    if n_samples != spec.num_samples:
        raise SystemExit(
            f"{size}: expected {spec.num_samples} samples, got {n_samples}"
        )
    print(f"{size}: ok ({n_samples} samples, {n_variants} variants)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--size",
        choices=list(SPECS),
        help="Which fixture to generate.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify existing fixtures rather than regenerate.",
    )
    parser.add_argument("--all", action="store_true", help="Generate every fixture.")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    if args.check:
        targets = [args.size] if args.size else list(SPECS)
        for t in targets:
            check_fixture(t)
        return

    targets = list(SPECS) if args.all else [args.size]
    if targets == [None]:
        parser.error("either --size or --all is required")
    for t in targets:
        build_fixture(t)


if __name__ == "__main__":
    main()
