"""Generate synthetic VCZ fixtures + phenotypes for the validation suite.

Two sizes:

- ``small`` — 200 diploid samples, ~500 biallelic variants. Used by
  qctool, PLINK 1.9, bgenix, REGENIE.
- ``large`` — 5000 diploid samples, ~20000 variants. Used by BOLT-LMM,
  which requires realistic sample counts to fit a null model.

Each fixture writes (under ``../datasets/validation/``, relative to
the vcztools repo root):

- ``<size>_unphased.vcz/`` and ``<size>_phased.vcz/`` — two Zarr v2 VCZ
  stores produced by ``bio2zarr.tskit.convert`` from the same
  simulation; only ``call_genotype_phased`` differs.
- ``<size>.pheno.tsv`` — a REGENIE/BOLT-style phenotype file
  (``FID IID Y1``) generated by tstrait from the source tree sequence.
  Shared between the phased and unphased stores.
- ``<size>.vcz.ready`` — marker file (sibling to the stores) signalling
  that both stores were built; consumed by the Makefile.

Phenotypes come from ``tstrait`` over the *source tree sequence* so the
genetic architecture is realistic enough that LMM tools can fit a null
model. The phenotype values themselves are not load-bearing for our
checks (we compare allele frequencies, not effect sizes).
"""

from __future__ import annotations

import dataclasses
import logging
import pathlib
import shutil

import bio2zarr.tskit as b2z_tskit
import click
import msprime
import numpy as np
import pandas as pd
import tskit
import tstrait
import zarr

logger = logging.getLogger(__name__)

HERE = pathlib.Path(__file__).parent
# Fixtures live outside the repo. Default location is
# ``../datasets/validation`` (relative to the vcztools repo root) so
# recursive searches over the working tree don't blow up on them.
DATA_DIR = HERE.parent.parent / "datasets" / "validation"

POPULATION_SIZE = 10_000
MUTATION_RATE = 1e-7
RECOMBINATION_RATE = 1e-8


@dataclasses.dataclass(frozen=True)
class FixtureSpec:
    name: str
    num_samples: int
    seq_length: float
    target_variants: int
    seed: int


SPECS: dict[str, FixtureSpec] = {
    "small": FixtureSpec(
        name="small",
        num_samples=200,
        seq_length=5e4,
        target_variants=1000,
        seed=42,
    ),
    "large": FixtureSpec(
        name="large",
        num_samples=5000,
        seq_length=5e5,
        target_variants=20_000,
        seed=43,
    ),
}


def simulate(spec: FixtureSpec) -> tskit.TreeSequence:
    ts = msprime.sim_ancestry(
        samples=spec.num_samples,
        sequence_length=spec.seq_length,
        recombination_rate=RECOMBINATION_RATE,
        population_size=POPULATION_SIZE,
        random_seed=spec.seed,
    )
    ts = msprime.sim_mutations(ts, rate=MUTATION_RATE, random_seed=spec.seed)
    logger.info(
        "Simulated %s: %d samples (diploid), %d variants",
        spec.name,
        spec.num_samples,
        ts.num_sites,
    )
    return ts


VARIANT_ID_BUCKETS: tuple[str, ...] = (
    "rs{i}",
    "rs_var_{i:08d}",
    "rs_variant_{i:010d}_chr_{c:02d}_pos_{p:010d}",
)
"""Three format strings cycled across the variants axis to produce a
deterministic mix of short (3–7 byte), medium (15 byte), and long
(~46 byte) variant IDs. Lengths comfortably fit under
:class:`vcztools.bgen.BgenEncoder`'s default
``total_string_length=64`` (which budgets all five string fields
combined), so the encoder's defaults still apply when this fixture
is fed through it.
"""


def _make_variant_ids(positions: np.ndarray, contigs: np.ndarray) -> np.ndarray:
    out = np.empty(positions.shape, dtype=np.dtypes.StringDType())
    for i in range(positions.size):
        template = VARIANT_ID_BUCKETS[i % len(VARIANT_ID_BUCKETS)]
        out[i] = template.format(i=i, c=int(contigs[i]), p=int(positions[i]))
    return out


def _convert_to_vcz(ts: tskit.TreeSequence, vcz_path: pathlib.Path) -> zarr.Group:
    """Run ``bio2zarr.tskit.convert`` into ``vcz_path`` (overwriting any
    existing store) and return the opened group in r+ mode.

    Individuals are named ``s0, s1, ...`` via the VCF-model mapping,
    so the ``sample_id`` array in the resulting VCZ store, the
    ``.fam`` written by view-plink, the ``.sample`` written by
    view-bgen, and the pheno file written by :func:`simulate_phenotype`
    all share the same short, predictable naming.
    """
    if vcz_path.exists():
        # bio2zarr refuses to overwrite an existing store; clean up first.
        shutil.rmtree(vcz_path)
    individual_names = [f"s{i}" for i in range(ts.num_individuals)]
    mapping = ts.map_to_vcf_model(individual_names=individual_names)
    b2z_tskit.convert(
        ts,
        str(vcz_path),
        model_mapping=mapping,
        variants_chunk_size=1000,
        samples_chunk_size=1000,
        worker_processes=0,
        show_progress=False,
    )
    return zarr.open_group(str(vcz_path), mode="r+")


def _inject_variant_ids(group: zarr.Group) -> None:
    """Add a ``variant_id`` array to ``group`` with deterministic
    variable-length IDs derived from variant position and contig.

    bio2zarr.tskit.convert does not populate variant_id (tskit uses
    positional numbering, not RS-style IDs). Inject deterministic
    variable-length IDs so the downstream-tool round-trip checks have a
    non-trivial signal to verify.
    """
    positions = group["variant_position"][:]
    contigs = group["variant_contig"][:]
    ids = _make_variant_ids(positions, contigs)
    variants_chunk = group["variant_position"].chunks[0]
    variant_id_arr = group.create_array(
        "variant_id",
        shape=ids.shape,
        chunks=(variants_chunk,),
        dtype=np.dtypes.StringDType(),
    )
    variant_id_arr[:] = ids
    # vcztools uses the zarr-v2 `_ARRAY_DIMENSIONS` attribute (and the
    # v3 `dimension_names` metadata) to identify the variants axis on
    # every variant-scoped field. bio2zarr writes v2 by default, so
    # set the v2 attribute on the array we just appended.
    variant_id_arr.attrs["_ARRAY_DIMENSIONS"] = ["variants"]


def write_vcz(ts: tskit.TreeSequence, vcz_path: pathlib.Path, *, phased: bool) -> None:
    group = _convert_to_vcz(ts, vcz_path)
    # tskit data is always phased; bio2zarr writes call_genotype_phased
    # = True. The unphased variant flattens the flag so vcztools emits
    # standard unphased BGEN (and PLINK, which has no phase concept).
    # The phased variant leaves the flag set, exercising vcztools'
    # phased-BGEN code path against downstream tools.
    if not phased and "call_genotype_phased" in group.array_keys():
        group["call_genotype_phased"][...] = False
    _inject_variant_ids(group)
    _inject_missing_calls(group, fraction=MISSING_FRACTION)
    logger.info("Wrote VCZ store at %s", vcz_path)


def write_haploid_vcz(ts: tskit.TreeSequence, vcz_path: pathlib.Path) -> None:
    """Write a uniform-haploid VCZ store derived from a diploid
    simulation. The first allele of every diploid call becomes the
    haploid call; the ploidy axis is collapsed to size 1.
    """
    group = _convert_to_vcz(ts, vcz_path)
    gt = group["call_genotype"]
    diploid_values = gt[...]
    haploid_values = diploid_values[:, :, 0:1].copy()
    chunks = gt.chunks
    haploid_chunks = (chunks[0], chunks[1], 1)
    del group["call_genotype"]
    haploid_arr = group.create_array(
        "call_genotype",
        shape=haploid_values.shape,
        chunks=haploid_chunks,
        dtype=np.int8,
    )
    haploid_arr[:] = haploid_values
    haploid_arr.attrs["_ARRAY_DIMENSIONS"] = ["variants", "samples", "ploidy"]
    if "call_genotype_phased" in group.array_keys():
        group["call_genotype_phased"][...] = False
    _inject_variant_ids(group)
    logger.info("Wrote haploid VCZ store at %s", vcz_path)


HAPLOID_SAMPLE_STRIDE = 3
"""Sample-index modulus for haploid samples in the mixed-ploidy fixture
(``idx % HAPLOID_SAMPLE_STRIDE == 0`` => haploid). 1/3 of samples are
haploid, matching X-chromosome-style data where the haploid fraction
is the male subset.
"""


def write_mixed_ploidy_vcz(ts: tskit.TreeSequence, vcz_path: pathlib.Path) -> None:
    """Write a mixed-ploidy VCZ store. Some samples are haploid (slot 1
    masked to ``-2``, the BGEN haploid-padding sentinel), the rest stay
    diploid.
    """
    group = _convert_to_vcz(ts, vcz_path)
    gt = group["call_genotype"]
    values = gt[...]
    n_samples = values.shape[1]
    haploid_mask = np.arange(n_samples) % HAPLOID_SAMPLE_STRIDE == 0
    values[:, haploid_mask, 1] = -2
    gt[:] = values
    if "call_genotype_phased" in group.array_keys():
        group["call_genotype_phased"][...] = False
    _inject_variant_ids(group)
    logger.info(
        "Wrote mixed-ploidy VCZ store at %s (%d/%d samples haploid)",
        vcz_path,
        int(haploid_mask.sum()),
        n_samples,
    )


MISSING_FRACTION = 0.01


def _inject_missing_calls(group: zarr.Group, *, fraction: float) -> None:
    """Mark ``fraction`` of (variant, sample) calls as fully missing.

    "Fully missing" means every ploidy slot of the call is set to
    ``-1`` and the matching ``call_genotype_mask`` entries are set to
    ``True``. This mirrors how a genotyping caller emits no-calls in
    practice — a sample either has a complete diploid call or none at
    all.

    Missing positions are picked deterministically: every ``stride``-th
    flat (variant, sample) index, where ``stride = round(1/fraction)``.
    Variants that would become monomorphic under that mask (rare for
    1% missingness — only a handful of singleton-ALT variants in the
    fixture) are reverted to their full-call state, so every emitted
    variant retains both alleles. REGENIE refuses to fit step-1 blocks
    containing zero-variance SNPs, so this revert step keeps the
    downstream surface clean without changing the fraction
    appreciably.
    """
    gt = group["call_genotype"]
    n_variants, n_samples, _ploidy = gt.shape
    n_total = n_variants * n_samples
    stride = int(round(1.0 / fraction))
    flat_missing = np.zeros(n_total, dtype=bool)
    flat_missing[::stride] = True
    missing_mask = flat_missing.reshape(n_variants, n_samples)

    gt_values = gt[:]
    # Tentative: where the mask says missing, both alleles are -1.
    tentative = gt_values.copy()
    tentative[missing_mask] = -1
    # Per-variant ALT count over non-missing alleles, and total non-
    # missing-allele count: monomorphic iff alt_count is 0 or equals
    # the total non-missing.
    non_missing_alleles = tentative >= 0
    n_alleles = non_missing_alleles.sum(axis=(1, 2))
    alt_alleles = (tentative > 0).sum(axis=(1, 2))
    mono = (alt_alleles == 0) | (alt_alleles == n_alleles)
    if mono.any():
        logger.info(
            "Reverting missing calls on %d would-be-monomorphic variants",
            int(mono.sum()),
        )
        missing_mask[mono, :] = False
    gt_values[missing_mask] = -1
    gt[:] = gt_values
    if "call_genotype_mask" in group.array_keys():
        mask_arr = group["call_genotype_mask"]
        mask_values = mask_arr[:]
        mask_values[missing_mask] = True
        mask_arr[:] = mask_values
    logger.info(
        "Injected %d missing calls (%.2f%% of %d total)",
        int(missing_mask.sum()),
        100.0 * missing_mask.sum() / n_total,
        n_total,
    )


def simulate_phenotype(
    ts: tskit.TreeSequence,
    spec: FixtureSpec,
    out_path: pathlib.Path,
) -> None:
    # 100 causal sites, heritability 0.5 — enough genetic signal that a
    # null model fit is well-conditioned.
    n_causal = min(100, ts.num_sites)
    model = tstrait.trait_model(distribution="normal", mean=0, var=1)
    sim_result = tstrait.sim_phenotype(
        ts=ts,
        num_causal=n_causal,
        model=model,
        h2=0.5,
        random_seed=spec.seed,
    )
    pheno = sim_result.phenotype
    # IIDs match the s0, s1, ... naming carried by the VCZ store's
    # ``sample_id`` array and the ``.fam`` written by view-plink.
    # FID="0" follows view-plink's .fam convention so the pheno file
    # feeds straight into REGENIE / BOLT on PLINK input without any
    # in-test rewrite; BGEN consumers see ID_1=ID_2=s_N in the
    # ``.sample`` and remap its family column to "0" to line up
    # (FID, IID) with the .fam.
    iids = [f"s{int(i)}" for i in pheno["individual_id"]]
    df = pd.DataFrame(
        {
            "FID": "0",
            "IID": iids,
            "Y1": pheno["phenotype"].astype(np.float64),
        }
    )
    df.to_csv(out_path, sep="\t", index=False)
    logger.info("Wrote phenotype file %s (%d rows)", out_path, len(df))


def build_fixture(size: str) -> None:
    spec = SPECS[size]
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    unphased_path = DATA_DIR / f"{size}_unphased.vcz"
    phased_path = DATA_DIR / f"{size}_phased.vcz"
    pheno_path = DATA_DIR / f"{size}.pheno.tsv"

    ts = simulate(spec)
    # Two stores per size, one msprime simulation. The fixtures share
    # genotypes; only `call_genotype_phased` differs.
    write_vcz(ts, unphased_path, phased=False)
    write_vcz(ts, phased_path, phased=True)
    simulate_phenotype(ts, spec, pheno_path)

    # Single marker per size: presence indicates both stores are
    # complete. Lives outside the VCZ stores so zarr doesn't warn
    # about unrecognised hierarchy components.
    marker = DATA_DIR / f"{size}.vcz.ready"
    marker.write_text(
        f"size={size}\nnum_samples={spec.num_samples}\n"
        f"num_variants={ts.num_sites}\nseed={spec.seed}\n"
    )
    logger.info(
        "Fixture %s ready (unphased=%s, phased=%s)", size, unphased_path, phased_path
    )


PLOIDY_KINDS = ("haploid", "mixed_ploidy", "varied_strings")
"""Supported ``--kind`` values: single-store fixtures derived from the
``small`` simulation. ``<DATA_DIR>/<kind>.vcz`` plus a
``<DATA_DIR>/<kind>.vcz.ready`` marker.

``haploid`` and ``mixed_ploidy`` exercise the BGEN encoder paths
against different ploidy shapes; ``varied_strings`` rewrites
``contig_id``, ``variant_contig``, and ``variant_allele`` so all four
actual-length BGEN string fields (chrom, allele1, allele2, variant_id)
vary across the fixture, exercising every per-variant length-prefix
path in the encoders."""


VARIED_CONTIG_IDS: tuple[str, ...] = (
    "1",
    "chr_02",
    "X",
    "supercontig_chr22_alt",
)
"""Contig names of varying byte length (1, 6, 1, 21 bytes) used by the
``varied_strings`` fixture. Variants are round-robin-assigned across
these four entries so every chrom-length code path runs."""


VARIED_ALLELE_RECIPES: tuple[tuple[str, str], ...] = (
    ("A", "T"),
    ("AT", "A"),
    ("G", "GTAC"),
    ("ACGT", "TGCA"),
    ("AAAAAAAAAA", "A"),
    ("C", "CGTACGTACG"),
)
"""(REF, ALT) recipes cycled across the variants axis of the
``varied_strings`` fixture. Mixes SNPs and indels with REF/ALT byte
lengths from 1 to 10. Applied to a copy of every variant's alleles so
genotype values (0=REF, 1=ALT) stay valid."""


def write_varied_strings_vcz(ts: tskit.TreeSequence, vcz_path: pathlib.Path) -> None:
    """Write a VCZ where chrom, allele1, allele2, and variant_id all
    vary in byte length across the variants axis.

    Reuses the ``small`` simulation for genotypes / samples. Rewrites:

    - ``contig_id`` with :data:`VARIED_CONTIG_IDS` (4 contigs of byte
      lengths 1, 6, 1, 21).
    - ``variant_contig`` to cycle each variant through the four contigs.
    - ``variant_allele`` so every variant's (REF, ALT) pair is drawn from
      :data:`VARIED_ALLELE_RECIPES`; genotypes are untouched (0=REF,
      1=ALT regardless of allele length).
    - ``variant_id`` via :func:`_inject_variant_ids` (same variable-
      length scheme as the diploid fixtures).

    No PLINK output is produced from this store: PLINK 1.9 only accepts
    a fixed set of chromosome names without ``--allow-extra-chr``, and
    keeping the suite simple is more valuable than smuggling that flag
    through every PLINK invocation. The store is BGEN-only.
    """
    group = _convert_to_vcz(ts, vcz_path)

    contig_arr = group["contig_id"]
    new_contigs = np.array(list(VARIED_CONTIG_IDS), dtype=contig_arr.dtype)
    del group["contig_id"]
    new_contig_arr = group.create_array(
        "contig_id",
        shape=new_contigs.shape,
        chunks=(len(new_contigs),),
        dtype=contig_arr.dtype,
    )
    new_contig_arr[:] = new_contigs
    new_contig_arr.attrs["_ARRAY_DIMENSIONS"] = ["contigs"]

    variant_contig_arr = group["variant_contig"]
    n_variants = variant_contig_arr.shape[0]
    new_variant_contig = (np.arange(n_variants) % len(VARIED_CONTIG_IDS)).astype(
        variant_contig_arr.dtype
    )
    variant_contig_arr[:] = new_variant_contig

    variant_allele_arr = group["variant_allele"]
    new_alleles = np.empty(variant_allele_arr.shape, dtype=variant_allele_arr.dtype)
    new_alleles[:] = ""
    for i in range(n_variants):
        ref, alt = VARIED_ALLELE_RECIPES[i % len(VARIED_ALLELE_RECIPES)]
        new_alleles[i, 0] = ref
        if new_alleles.shape[1] >= 2:
            new_alleles[i, 1] = alt
    variant_allele_arr[:] = new_alleles

    # msprime occasionally produces tri-allelic recurrent mutations
    # (genotype value 2 referencing the third allele slot). The
    # biallelic rewrite above collapses the third slot to "", so any
    # remaining 2 in call_genotype would reference an allele that no
    # longer exists. Fold those into the ALT bucket (value 1) so every
    # call is valid under the biallelic recipe.
    gt = group["call_genotype"]
    gt_values = gt[:]
    gt_values[gt_values >= 2] = 1
    gt[:] = gt_values

    if "call_genotype_phased" in group.array_keys():
        group["call_genotype_phased"][...] = False

    _inject_variant_ids(group)
    logger.info(
        "Wrote varied-strings VCZ store at %s (%d variants, %d contigs)",
        vcz_path,
        n_variants,
        len(VARIED_CONTIG_IDS),
    )


def build_ploidy_fixture(kind: str) -> None:
    """Build the ``haploid``, ``mixed_ploidy``, or ``varied_strings``
    single-store fixture.

    All three reuse the ``small`` simulation so genotype content
    matches what the diploid fixtures see. No phenotype file is
    generated: REGENIE / BOLT (the only phenotype consumers) are
    diploid-only and are not exercised on these stores.
    """
    if kind not in PLOIDY_KINDS:
        raise ValueError(f"unknown ploidy kind {kind!r}")
    spec = SPECS["small"]
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    vcz_path = DATA_DIR / f"{kind}.vcz"

    ts = simulate(spec)
    if kind == "haploid":
        write_haploid_vcz(ts, vcz_path)
    elif kind == "mixed_ploidy":
        write_mixed_ploidy_vcz(ts, vcz_path)
    else:
        write_varied_strings_vcz(ts, vcz_path)

    marker = DATA_DIR / f"{kind}.vcz.ready"
    marker.write_text(
        f"kind={kind}\nnum_samples={spec.num_samples}\n"
        f"num_variants={ts.num_sites}\nseed={spec.seed}\n"
    )
    logger.info("Ploidy fixture %s ready (%s)", kind, vcz_path)


def check_fixture(size: str) -> None:
    spec = SPECS[size]
    pheno_path = DATA_DIR / f"{size}.pheno.tsv"
    marker = DATA_DIR / f"{size}.vcz.ready"

    if not marker.exists():
        raise SystemExit(f"missing fixture marker {marker}")
    if not pheno_path.exists():
        raise SystemExit(f"missing phenotype file {pheno_path}")

    for variant in ("unphased", "phased"):
        vcz_path = DATA_DIR / f"{size}_{variant}.vcz"
        group = zarr.open_group(str(vcz_path), mode="r")
        n_samples = group["sample_id"].shape[0]
        n_variants = group["variant_position"].shape[0]
        if n_samples != spec.num_samples:
            raise SystemExit(
                f"{size}_{variant}: expected {spec.num_samples} samples, "
                f"got {n_samples}"
            )
        print(f"{size}_{variant}: ok ({n_samples} samples, {n_variants} variants)")


@click.command(help=__doc__)
@click.option(
    "--size",
    type=click.Choice(list(SPECS)),
    default=None,
    help="Which size fixture (diploid) to generate.",
)
@click.option(
    "--kind",
    type=click.Choice(list(PLOIDY_KINDS)),
    default=None,
    help="Which ploidy fixture (single store, small simulation) to generate.",
)
@click.option(
    "--check",
    is_flag=True,
    help="Verify existing fixtures rather than regenerate.",
)
@click.option(
    "--all",
    "all_sizes",
    is_flag=True,
    help="Generate every fixture.",
)
def main(size: str | None, kind: str | None, check: bool, all_sizes: bool) -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    if check:
        targets = [size] if size is not None else list(SPECS)
        for t in targets:
            check_fixture(t)
        return

    if kind is not None:
        if size is not None or all_sizes:
            raise click.UsageError("--kind is mutually exclusive with --size / --all")
        build_ploidy_fixture(kind)
        return

    if all_sizes:
        targets = list(SPECS)
    elif size is not None:
        targets = [size]
    else:
        raise click.UsageError("one of --size, --kind, or --all is required")
    for t in targets:
        build_fixture(t)


if __name__ == "__main__":
    main()
