"""REGENIE reads vcztools view-plink and view-bgen output and reports
the same per-variant ALT allele frequencies we compute from the
source VCZ.

For each input format (PLINK fileset, BGEN at compression level -1
and 0) we:

1. Fit a step-1 null model on the synthetic tstrait phenotype.
2. Run step-2 association testing.
3. Parse the per-variant ``.regenie`` output and assert ``A1FREQ``
   matches ``reference.compute_variant_stats.alt_freq``.

REGENIE's ``--minMAC 0.5`` keeps every variant in the output (the
default cutoff drops low-MAC sites). BGEN input takes the
``--ref-first`` flag so the alleles line up with how vcztools writes
them (REF as ALLELE0, ALT as ALLELE1).
"""

from __future__ import annotations

import pathlib

import numpy as np
import pandas as pd
import pytest

from . import conftest as cfg
from . import helpers, reference


def _remap_pheno_fid0(pheno_path: pathlib.Path, out_path: pathlib.Path) -> pathlib.Path:
    """Rewrite a phenotype file's FID column to "0" so it matches the
    .fam written by ``view-plink``. The phenotype file generated by
    ``generate_data.py`` uses FID=IID (the BGEN convention)."""
    df = pd.read_csv(pheno_path, sep=r"\s+", engine="python")
    df["FID"] = "0"
    df.to_csv(out_path, sep=" ", index=False)
    return out_path


def _run_step1_plink(
    regenie: pathlib.Path,
    bed_prefix: pathlib.Path,
    pheno_path: pathlib.Path,
    out_prefix: pathlib.Path,
) -> pathlib.Path:
    helpers.run_tool(
        [
            str(regenie),
            "--step",
            "1",
            "--bed",
            str(bed_prefix),
            "--phenoFile",
            str(pheno_path),
            "--bsize",
            "100",
            "--qt",
            "--lowmem",
            "--lowmem-prefix",
            str(out_prefix.parent / "lowmem"),
            "--out",
            str(out_prefix),
        ]
    )
    return out_prefix.with_name(out_prefix.name + "_pred.list")


def _run_step1_bgen(
    regenie: pathlib.Path,
    bgen_path: pathlib.Path,
    sample_path: pathlib.Path,
    pheno_path: pathlib.Path,
    out_prefix: pathlib.Path,
) -> pathlib.Path:
    helpers.run_tool(
        [
            str(regenie),
            "--step",
            "1",
            "--bgen",
            str(bgen_path),
            "--sample",
            str(sample_path),
            "--ref-first",
            "--phenoFile",
            str(pheno_path),
            "--bsize",
            "100",
            "--qt",
            "--lowmem",
            "--lowmem-prefix",
            str(out_prefix.parent / "lowmem"),
            "--out",
            str(out_prefix),
        ]
    )
    return out_prefix.with_name(out_prefix.name + "_pred.list")


def _run_step2(
    regenie: pathlib.Path,
    pred_list: pathlib.Path,
    pheno_path: pathlib.Path,
    out_prefix: pathlib.Path,
    *,
    bed_prefix: pathlib.Path | None = None,
    bgen_path: pathlib.Path | None = None,
    sample_path: pathlib.Path | None = None,
) -> pd.DataFrame:
    cmd = [
        str(regenie),
        "--step",
        "2",
        "--phenoFile",
        str(pheno_path),
        "--bsize",
        "100",
        "--qt",
        "--pred",
        str(pred_list),
        "--minMAC",
        "0.5",
        "--out",
        str(out_prefix),
    ]
    if bed_prefix is not None:
        cmd += ["--bed", str(bed_prefix)]
    if bgen_path is not None:
        cmd += [
            "--bgen",
            str(bgen_path),
            "--sample",
            str(sample_path),
            "--ref-first",
        ]
    helpers.run_tool(cmd)
    return pd.read_csv(
        out_prefix.with_name(out_prefix.name + "_Y1.regenie"),
        sep=r"\s+",
        engine="python",
    )


class TestRegenieFromPlinkInput:
    def test_a1freq_matches_reference(
        self, tmp_path, regenie_bin, small_unphased_fixture
    ):
        pheno = _remap_pheno_fid0(
            small_unphased_fixture.pheno_path, tmp_path / "pheno.tsv"
        )
        pred = _run_step1_plink(
            regenie_bin,
            small_unphased_fixture.plink_prefix,
            pheno,
            tmp_path / "step1",
        )
        df = _run_step2(
            regenie_bin,
            pred,
            pheno,
            tmp_path / "step2",
            bed_prefix=small_unphased_fixture.plink_prefix,
        )
        ref = reference.compute_variant_stats(small_unphased_fixture.vcz_path)
        biallelic = ref.n_alleles == 2
        assert len(df) == int(biallelic.sum())
        # REGENIE writes A1FREQ to 6 decimal places. With 1% missing
        # the per-variant denominator is no longer a power-of-10
        # friendly 400, so fractions like 291/396 don't have an exact
        # 6-decimal representation — the diff is up to ~5e-7. The
        # computation itself round-trips exactly (vcztools writes hard
        # calls); this tolerance only covers REGENIE's output
        # formatter.
        np.testing.assert_allclose(
            df["A1FREQ"].to_numpy(),
            ref.alt_freq[biallelic],
            atol=5e-7,
        )


class TestRegenieFromBgenInput:
    @pytest.mark.parametrize("level", cfg.BGEN_LEVELS)
    def test_a1freq_matches_reference(
        self, tmp_path, regenie_bin, small_unphased_fixture, level
    ):
        bgen, sample = cfg.bgen_for_level(small_unphased_fixture, level)
        # BGEN samples have FID=IID=tsk_N, matching the phenotype file
        # written by generate_data.py — no remap needed for BGEN input.
        pred = _run_step1_bgen(
            regenie_bin,
            bgen,
            sample,
            small_unphased_fixture.pheno_path,
            tmp_path / "step1",
        )
        df = _run_step2(
            regenie_bin,
            pred,
            small_unphased_fixture.pheno_path,
            tmp_path / "step2",
            bgen_path=bgen,
            sample_path=sample,
        )
        ref = reference.compute_variant_stats(small_unphased_fixture.vcz_path)
        biallelic = ref.n_alleles == 2
        assert len(df) == int(biallelic.sum())
        # Same display-precision dodge as the PLINK input case. The
        # numerical round-trip is exact because vcztools writes hard
        # calls; the ~5e-7 slack covers REGENIE's 6-decimal A1FREQ
        # output formatter.
        np.testing.assert_allclose(
            df["A1FREQ"].to_numpy(),
            ref.alt_freq[biallelic],
            atol=5e-7,
        )


class TestRegenieVariantIds:
    def test_plink_input_id_column_matches_reference(
        self, tmp_path, regenie_bin, small_unphased_fixture
    ):
        pheno = _remap_pheno_fid0(
            small_unphased_fixture.pheno_path, tmp_path / "pheno.tsv"
        )
        pred = _run_step1_plink(
            regenie_bin,
            small_unphased_fixture.plink_prefix,
            pheno,
            tmp_path / "step1",
        )
        df = _run_step2(
            regenie_bin,
            pred,
            pheno,
            tmp_path / "step2",
            bed_prefix=small_unphased_fixture.plink_prefix,
        )
        ref = reference.compute_variant_stats(small_unphased_fixture.vcz_path)
        biallelic = ref.n_alleles == 2
        ids = reference.variant_ids(small_unphased_fixture.vcz_path)[biallelic]
        np.testing.assert_array_equal(df["ID"].astype(str).to_numpy(), ids)

    @pytest.mark.parametrize("level", cfg.BGEN_LEVELS)
    def test_bgen_input_id_column_matches_reference(
        self, tmp_path, regenie_bin, small_unphased_fixture, level
    ):
        bgen, sample = cfg.bgen_for_level(small_unphased_fixture, level)
        pred = _run_step1_bgen(
            regenie_bin,
            bgen,
            sample,
            small_unphased_fixture.pheno_path,
            tmp_path / "step1",
        )
        df = _run_step2(
            regenie_bin,
            pred,
            small_unphased_fixture.pheno_path,
            tmp_path / "step2",
            bgen_path=bgen,
            sample_path=sample,
        )
        ref = reference.compute_variant_stats(small_unphased_fixture.vcz_path)
        biallelic = ref.n_alleles == 2
        ids = reference.variant_ids(small_unphased_fixture.vcz_path)[biallelic]
        # BgenEncoder NUL-pads string fields to a fixed width per the
        # BGEN spec. bgenix and qctool strip the padding on read;
        # REGENIE does not, so its ID column comes back as
        # "rs0\x00\x00..." for the encoder fixture. Strip here so the
        # round-trip check measures content rather than padding policy.
        regenie_ids = np.array(
            [s.rstrip("\x00") for s in df["ID"].astype(str).to_numpy()]
        )
        np.testing.assert_array_equal(regenie_ids, ids)


class TestRegeniePhasedBgen:
    """REGENIE rejects phased BGEN with the diagnostic ``only unphased
    bgen are supported``. Pin that so a future REGENIE release that
    adds phased support surfaces here."""

    def test_rejects_phased_bgen(self, tmp_path, regenie_bin, small_phased_fixture):
        result = helpers.run_tool(
            [
                str(regenie_bin),
                "--step",
                "1",
                "--bgen",
                str(small_phased_fixture.bgen_minus1),
                "--sample",
                str(small_phased_fixture.sample_path),
                "--ref-first",
                "--phenoFile",
                str(small_phased_fixture.pheno_path),
                "--bsize",
                "100",
                "--qt",
                "--lowmem",
                "--lowmem-prefix",
                str(tmp_path / "lowmem"),
                "--out",
                str(tmp_path / "step1"),
            ],
            check=False,
        )
        combined = result.stdout + result.stderr
        assert "only unphased bgen are supported" in combined, (
            f"REGENIE didn't surface the phased-BGEN diagnostic; "
            f"stdout+stderr tail:\n{combined[-2000:]}"
        )
