"""REGENIE reads vcztools view-plink and view-bgen output and reports
the same per-variant ALT allele frequencies we compute from the
source VCZ.

For each input format (PLINK fileset, BGEN at compression level -1
and 0) we:

1. Fit a step-1 null model on the synthetic tstrait phenotype.
2. Run step-2 association testing.
3. Parse the per-variant ``.regenie`` output and assert ``A1FREQ``
   matches ``reference.compute_variant_stats.alt_freq``.

REGENIE's ``--minMAC 0.5`` keeps every variant in the output (the
default cutoff drops low-MAC sites). BGEN input takes the
``--ref-first`` flag so the alleles line up with how vcztools writes
them (REF as ALLELE0, ALT as ALLELE1).
"""

from __future__ import annotations

import pathlib

import numpy as np
import pandas as pd
import pytest

from . import helpers, reference


def _remap_pheno_fid0(pheno_path: pathlib.Path, out_path: pathlib.Path) -> pathlib.Path:
    """Rewrite a phenotype file's FID column to "0" so it matches the
    .fam written by ``view-plink``. The phenotype file generated by
    ``generate_data.py`` uses FID=IID (the BGEN convention)."""
    df = pd.read_csv(pheno_path, sep=r"\s+", engine="python")
    df["FID"] = "0"
    df.to_csv(out_path, sep=" ", index=False)
    return out_path


def _run_step1_plink(
    regenie: pathlib.Path,
    bed_prefix: pathlib.Path,
    pheno_path: pathlib.Path,
    out_prefix: pathlib.Path,
) -> pathlib.Path:
    helpers.run_tool(
        [
            str(regenie),
            "--step",
            "1",
            "--bed",
            str(bed_prefix),
            "--phenoFile",
            str(pheno_path),
            "--bsize",
            "100",
            "--qt",
            "--lowmem",
            "--lowmem-prefix",
            str(out_prefix.parent / "lowmem"),
            "--out",
            str(out_prefix),
        ]
    )
    return out_prefix.with_name(out_prefix.name + "_pred.list")


def _run_step1_bgen(
    regenie: pathlib.Path,
    bgen_path: pathlib.Path,
    sample_path: pathlib.Path,
    pheno_path: pathlib.Path,
    out_prefix: pathlib.Path,
) -> pathlib.Path:
    helpers.run_tool(
        [
            str(regenie),
            "--step",
            "1",
            "--bgen",
            str(bgen_path),
            "--sample",
            str(sample_path),
            "--ref-first",
            "--phenoFile",
            str(pheno_path),
            "--bsize",
            "100",
            "--qt",
            "--lowmem",
            "--lowmem-prefix",
            str(out_prefix.parent / "lowmem"),
            "--out",
            str(out_prefix),
        ]
    )
    return out_prefix.with_name(out_prefix.name + "_pred.list")


def _run_step2(
    regenie: pathlib.Path,
    pred_list: pathlib.Path,
    pheno_path: pathlib.Path,
    out_prefix: pathlib.Path,
    *,
    bed_prefix: pathlib.Path | None = None,
    bgen_path: pathlib.Path | None = None,
    sample_path: pathlib.Path | None = None,
) -> pd.DataFrame:
    cmd = [
        str(regenie),
        "--step",
        "2",
        "--phenoFile",
        str(pheno_path),
        "--bsize",
        "100",
        "--qt",
        "--pred",
        str(pred_list),
        "--minMAC",
        "0.5",
        "--out",
        str(out_prefix),
    ]
    if bed_prefix is not None:
        cmd += ["--bed", str(bed_prefix)]
    if bgen_path is not None:
        cmd += [
            "--bgen",
            str(bgen_path),
            "--sample",
            str(sample_path),
            "--ref-first",
        ]
    helpers.run_tool(cmd)
    return pd.read_csv(
        out_prefix.with_name(out_prefix.name + "_Y1.regenie"),
        sep=r"\s+",
        engine="python",
    )


class TestRegenieFromPlinkInput:
    def test_a1freq_matches_reference(self, tmp_path, regenie_bin, small_fixture):
        pheno = _remap_pheno_fid0(small_fixture.pheno_path, tmp_path / "pheno.tsv")
        pred = _run_step1_plink(
            regenie_bin,
            small_fixture.plink_prefix,
            pheno,
            tmp_path / "step1",
        )
        df = _run_step2(
            regenie_bin,
            pred,
            pheno,
            tmp_path / "step2",
            bed_prefix=small_fixture.plink_prefix,
        )
        ref = reference.compute_variant_stats(small_fixture.vcz_path)
        biallelic = ref.n_alleles == 2
        assert len(df) == int(biallelic.sum())
        np.testing.assert_allclose(
            df["A1FREQ"].to_numpy(),
            ref.alt_freq[biallelic],
            atol=1e-10,
        )


class TestRegenieFromBgenInput:
    @pytest.mark.parametrize("level", [-1, 0], ids=["lvl=-1", "lvl=0"])
    def test_a1freq_matches_reference(
        self, tmp_path, regenie_bin, small_fixture, level
    ):
        bgen = small_fixture.bgen_minus1 if level == -1 else small_fixture.bgen_stored
        # BGEN samples already have FID=IID=tsk_N, matching the
        # phenotype file as written by generate_data.py — no remap.
        pred = _run_step1_bgen(
            regenie_bin,
            bgen,
            small_fixture.sample_path,
            small_fixture.pheno_path,
            tmp_path / "step1",
        )
        df = _run_step2(
            regenie_bin,
            pred,
            small_fixture.pheno_path,
            tmp_path / "step2",
            bgen_path=bgen,
            sample_path=small_fixture.sample_path,
        )
        ref = reference.compute_variant_stats(small_fixture.vcz_path)
        biallelic = ref.n_alleles == 2
        assert len(df) == int(biallelic.sum())
        # BGEN dosages are 8-bit quantised, so allele frequency has
        # the same atol budget as qctool.
        np.testing.assert_allclose(
            df["A1FREQ"].to_numpy(),
            ref.alt_freq[biallelic],
            atol=5e-3,
        )
