name: CD

on:
  push:
    branches: [main, test-publish]
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build-sdist:
    if: github.repository_owner == 'sgkit-dev'
    name: Build sdist
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Build sdist
        run: uv build --sdist -o dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-sdist
          path: dist/*.tar.gz
          if-no-files-found: error

  build-wheels:
    if: github.repository_owner == 'sgkit-dev'
    needs: [build-sdist]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: build-sdist

      - name: Copy sdist
        run: cp *.tar.gz sdist.tar.gz

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: uv sync --locked --only-group wheels

      - name: Build wheels
        run: uv run --only-group wheels cibuildwheel sdist.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error

  publish-to-pypi:
    if: github.repository_owner == 'sgkit-dev' && github.event_name == 'release'
    needs: [build-sdist, build-wheels]
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/vcztools
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: dist
          merge-multiple: true

      - name: Show artifacts
        run: ls -lah dist

      - uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    if: github.repository_owner == 'sgkit-dev' && github.event_name == 'push' && (github.ref_name == 'test-publish' || startsWith(github.event.ref, 'refs/tags'))
    needs: [build-sdist, build-wheels]
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/vcztools

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: dist
          merge-multiple: true

      - name: Show artifacts
        run: ls -lah dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          repository-url: https://test.pypi.org/legacy/
